[tool.poetry]
name = "sherlock"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
certifi = ">=2019.6.16"
colorama = ">=0.4.1"
PySocks = ">=1.7.0"
requests = ">=2.22.0"
requests-futures = ">=1.0.0"
stem = ">=1.8.0"
torrequest = ">=0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sherlock = "sherlock.sherlock:main"
